### ISSUE TITLE
Atari ST palette data is incorrect

### ISSUE THREAD

**Issue by evldhs** [grahambates/gradient-blaster#1]
There are 4-bit nibbles produced also in Atari ST palette mode (should be 3-bit).

How to see the bug:
1. Launch the tool
2. Switch to Atari ST

See datas such as :
dc.w $ff0,$ff0,$ff0,$ff0,$ff4,$ff3,$ff3,$ff4
dc.w $ff3,$ff3,$ef5,$ff5,$ef4,$ef5,$ef5,$ff5
...
ST should be 0-7 only.

If the first control colour is black, it will fade with ST colours until it reaches the next control colour and then start to output 4-bit nibbles.  If the end control colour is black, the last part of the fade will be correct.  So it seems fades going from or to black works fine, otherwise not.

**Comment by grahambates** [comment]
Thanks for flagging. I'd broken this when adding the `amigaOcsLace` mode. Time for unit tests I think!
