### ISSUE TITLE
Support for Falcon/24-bit mode

### ISSUE THREAD

**Issue by mikrosk** [grahambates/gradient-blaster#3]
Just found your tool, I like it very much.

A small feature request: could you add also the full 24-bit scale for the Falcon format? As there is already a hardware which supports it (SuperVidel), the situation is similar as with ST vs STE palette: it's always a good idea to work natively with the better format.

**Comment by grahambates** [comment]
Glad you like the tool. I'll look definitely look into supporting this format. 

Do you happen to have a link for any reference info? Don't worry if not, I'll have a look.

**Comment by mikrosk** [comment]
It's just a simple R:G:0:B palette format. If you really want to take a look, check this out: http://hencox.gildaelectronics.se/homepage/Self/SuperVidelMemoryMap.pdf

**Comment by grahambates** [comment]
Ok I've added the new mode and the change should be live.

You're right, it was really straightforward. I was imagining that the bits might be reordered like for STE, but I forgot that the lower 2 bits are already empty for Falcon.

Let me know if there are any issues.

**Comment by mikrosk** [comment]
Many thanks, Graham!
